# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

target 'TestNumberFormatting' do
	source 'https://github.com/CocoaPods/Specs.git'
	pod 'PhoneNumberKit', '~> 1.2'
	pod 'AKNumericFormatter'
end
