# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

target 'FirebaseTest' do

	#firebase
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Messaging'

	#fabric
	pod 'Fabric'
	pod 'Crashlytics'

	#analytics
	pod 'Google/Analytics'
	
end
